name: konekto_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  table_calendar: ^3.0.0
  intl: ^0.20.2
  dotted_border: ^2.1.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: # Esta linha alinhada à esquerda
  uses-material-design: true # Esta linha indentada com dois espaços
  
  assets: # Esta linha indentada com dois espaços
    - assets/images/konekto_logo.png # Logo Konekto (fixa, fora das pastas de tenant)
    - assets/images/placeholder.png  # Imagens de fallback genéricas
    
    # Inclusão genérica da pasta raiz de tenants (para pegar JSONs na raiz de cada tenant, por exemplo)
    - assets/tenants/ # Esta linha indentada com quatro espaços
    
    # INCLUSÃO EXPLÍCITA DE CADA PASTA DE TENANT (RECOMENDADO PARA ROBUSTEZ)
    # Isso garante que TODO o conteúdo de cada pasta de tenant seja incluído.
    # Esta é a parte que você provavelmente sentiu falta.
    - assets/tenants/konekto_app/ # Inclui tudo dentro de konekto_app/
    - assets/tenants/beach_park/  # Inclui tudo dentro de beach_park/
    - assets/tenants/copacabana_palace/ # Inclui tudo dentro de copacabana_palace/

    # Além disso, para maior clareza e como uma camada extra de segurança, 
    # listamos as subpastas de imagens mais comuns DENTRO DE CADA TENANT.
    # Embora as linhas acima teoricamente já incluam isso, ser explícito pode evitar problemas.
    # Mantenha a indentação de 4 espaços.

    # Para konekto_app:
    - assets/tenants/konekto_app/images/
    - assets/tenants/konekto_app/images/banners/
    - assets/tenants/konekto_app/images/cardapio/
    - assets/tenants/konekto_app/images/cardapio/room_services/
    - assets/tenants/konekto_app/images/restaurantes/
    - assets/tenants/konekto_app/images/spa/
    - assets/tenants/konekto_app/images/eventos/
    - assets/tenants/konekto_app/images/mapa/
    - assets/tenants/konekto_app/images/passeios/
    - assets/tenants/konekto_app/images/logos/ 
    
    # Para beach_park:
    - assets/tenants/beach_park/images/
    - assets/tenants/beach_park/images/banners/
    - assets/tenants/beach_park/images/cardapio/
    - assets/tenants/beach_park/images/cardapio/room_services/
    - assets/tenants/beach_park/images/restaurantes/
    - assets/tenants/beach_park/images/spa/
    - assets/tenants/beach_park/images/eventos/
    - assets/tenants/beach_park/images/mapa/
    - assets/tenants/beach_park/images/passeios/
    - assets/tenants/beach_park/images/logos/ 
    
    # Para copacabana_palace:
    - assets/tenants/copacabana_palace/images/
    - assets/tenants/copacabana_palace/images/banners/
    - assets/tenants/copacabana_palace/images/cardapio/
    - assets/tenants/copacabana_palace/images/cardapio/room_services/
    - assets/tenants/copacabana_palace/images/restaurantes/
    - assets/tenants/copacabana_palace/images/spa/
    - assets/tenants/copacabana_palace/images/eventos/
    - assets/tenants/copacabana_palace/images/mapa/
    - assets/tenants/copacabana_palace/images/passeios/
    - assets/tenants/copacabana_palace/images/logos/ 
    
    # Se você adicionar mais tenants no futuro, lembre-se de adicionar suas pastas raiz e de imagens aqui!